### ISSUE TITLE
Is is possible to publish both "depth_registered/points" and "depth/color/points" for pointcloud topics?

### ISSUE THREAD

**Issue by fettahyildizz** [ros-drivers/rgbd_launch#51]
I am working on a large scale project and I want to use rs_rgbd.launch given in realsense2_camera package, which uses this repo, to publish depth_registered/points but my teammates are also using depth/color/points topic. Is it possible to arrange launch file in such a way that both topics would be published?

**Comment by 130s** [comment]
Closing.

This place is for discussing (almost-)verified bugs and proposed enhancement, and because development is stalled few people are watching here. Technical questions will get more attention somewhere else, e.g. https://answers.ros.org/questions/ and https://robotics.stackexchange.com/ so please ask elsewhere.
